config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :restaurants do
    collection do
      get 'search'
    end
    resources :reviews, except: [:show, :index]
  end

  get 'main/about'

  get 'main/contact'

  root 'restaurants#index'
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  mount_uploader :image, ImageUploader

  searchkick

  has_many :reviews

  validates :name, :address, :phone, :website, :image, presence: true

  validates :phone, format: {
    with: /\d{3}-\d{3}-\d{4}/,
    message: 'must be in the format 123-456-7890'
  }

  validates :website, format: {
    with: %r{https?://},
    message: 'must start with http:// or https://'
  }
  validates :address, format: {
    with: /\A\d+[^,]+,[^,]+, [A-Z]{2} \d{5}\z/,
    message: 'must be in the format 350 Fifth Avenue, New York, NY 10118'
  }
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :restaurant

  validates :rating, :comment, presence: true
  validates :rating, numericality: {
    only_integer: true,
    greater_than_or_equal_to: 1,
    less_than_or_equal_to: 5,
    message: 'can only be a whole number between 1 and 5'
  }
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :reviews, dependent: :destroy

  validates :first_name, :last_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :first_name
    devise_parameter_sanitizer.for(:sign_up) << :last_name
    devise_parameter_sanitizer.for(:account_update) << :first_name
    devise_parameter_sanitizer.for(:account_update) << :last_name
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def about
  end

  def contact
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]
  before_action :check_user, except: [:index, :show]

  def index
    @restaurants = Restaurant.all.order('created_at DESC')
                   .paginate(page: params[:page], per_page: 5)
  end

  def show
    @reviews = Review.where(restaurant_id: @restaurant.id)
               .order('created_at DESC')
    if @reviews.blank?
      @avg_rating = 0
    else
      @avg_rating = @reviews.average(:rating).round(2)
    end
  end

  def new
    @restaurant = Restaurant.new
  end

  def edit
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)

    respond_to do |format|
      if @restaurant.save
        format.html do
          redirect_to @restaurant,
                      notice: 'Restaurant was successfully created.'
        end
        format.json { render :show, status: :created, location: @restaurant }
      else
        format.html { render :new }
        format.json do
          render json: @restaurant.errors, status: :unprocessable_entity
        end
      end
    end
  end

  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html do
          redirect_to @restaurant,
                      notice: 'Restaurant was successfully updated.'
        end
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit }
        format.json do
          render json: @restaurant.errors, status: :unprocessable_entity
        end
      end
    end
  end

  def destroy
    @restaurant.destroy
    respond_to do |format|
      format.html do
        redirect_to restaurants_url,
                    notice: 'Restaurant was successfully destroyed.'
      end
      format.json { head :no_content }
    end
  end

  def search
    if params[:search].present?
      @restaurants = Restaurant.paginate(page: params[:page], per_page: 10)
                     .search(params[:search])
    else
      @restaurants = Restaurant.all.paginate(page: params[:page], per_page: 10)
    end
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant)
      .permit(:name, :address, :phone, :website, :image)
  end

  def check_user
    return if current_user.admin?
    redirect_to root_url, alert: 'Sorry, only admins can do that!'
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_review, only: [:edit, :update, :destroy]
  before_action :check_user, only: [:edit, :update, :destroy]
  before_action :set_restaurant

  def new
    @review = Review.new
  end

  def edit
  end

  def create
    @review = Review.new(review_params)
    @review.user_id = current_user.id
    @review.restaurant_id = @restaurant.id

    respond_to do |format|
      if @review.save
        format.html do
          redirect_to @restaurant, notice: 'Review was successfully created.'
        end
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json do
          render json: @review.errors, status: :unprocessable_entity
        end
      end
    end
  end

  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html do
          redirect_to restaurant_path(@restaurant),
                      notice: 'Review was successfully updated.'
        end
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json do
          render json: @review.errors, status: :unprocessable_entity
        end
      end
    end
  end

  def destroy
    @review.destroy
    respond_to do |format|
      format.html do
        redirect_to restaurant_path(@restaurant),
                    notice: 'Review was successfully destroyed.'
      end
      format.json { head :no_content }
    end
  end

  private

  def set_review
    @review = Review.find(params[:id])
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def review_params
    params.require(:review).permit(:rating, :comment)
  end

  def check_user
    return if (@review.user == current_user) || (current_user.admin?)
    redirect_to root_url, alert: 'Sorry, this review belongs to someone else'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join

    sentence = I18n.t('errors.messages.not_saved', count: resource.errors.count, resource: resource.class.model_name.human.downcase)

    html = <<-HTML
    <div class="alert alert-danger alert-dismissbale">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span>
        <span class="sr-only">Close</span>
      </button>
      <h4>#{sentence}</h4>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/_footer.html.erb
<div class= "row">
  <%= image_tag "https://s3.amazonaws.com/the-greasy-spoon-production/dirty_spoon.png", class: "img-responsive footer-img" %>
  <p>Copyright: Ryan Haase</p>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "The Greasy Spoon", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "About", main_about_path %></li>
        <li><%= link_to "Contact", main_contact_path %></li>
      </ul>
      <%= form_tag search_restaurants_path, method: :get, class: "navbar-form navbar-left" do %>
        <p>
          <%= text_field_tag :search, params[:search], class: "form-control" %>
          <%= submit_tag "Search", name: nil, class: "btn btn-default" %>
        </p>
      <% end %>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
          <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign up", new_user_registration_path %></li>
          <li><%= link_to "Sign in", new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TheGreasySpoon</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/navbar' %>

  <div class="row alert-row">
    <% if flash[:notice] %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:notice] %>
      </div>
    <% elsif flash[:error] %>
      <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:error] %>
      </div>
    <% elsif flash[:alert] %>
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert] %>
      </div>
    <% end %>
  </div>

  <div id="body" class="container">
    <%= yield %>
  </div>

  <footer>
    <%= render 'layouts/footer' %>
  </footer>
</body>
</html>

app/views/main/about.html.erb
<div class="well well-lg">
  <h1>Welcome to The Greasy Spoon!</h1>
  <h3>The Greasy Spoon is a Yelp clone built in Ruby on Rails</h3>
  <p>This app was built as a learning opportunity working with Ruby on Rails, jQuery Raty - A Star Rating Plugin, and Google Maps API.</p>
</div>

app/views/main/contact.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Contact me - I would love to hear from you!</h3>
  </div>
    <ul id="contact" class="list-group">
      <li class="list-group-item"><strong>Email:</strong> <a href="mailto:ryandhaase@gmail.com">ryandhaase@gmail.com</a></li>
      <li class="list-group-item"><strong>Portfolio:</strong> <a href="http://www.ryandhaase.engineer/">http://www.ryandhaase.engineer</a></li>
      <li class="list-group-item"><strong>GitHub:</strong> <a href="https://github.com/OggimusPrime">https://github.com/OggimusPrime</a></li>
    </ul>
</div>

app/views/restaurants/_form.html.erb
<%= form_for(@restaurant, html: { multipart: true }) do |f| %>
  <% if @restaurant.errors.any? %>
    <div id="error_explanation" class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
        <span class="sr-only">Close</span>
      </button>
      <h2><%= pluralize(@restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

      <ul>
      <% @restaurant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control", placeholder: "Panera Bread" %>
  </div>
  <div class="form-group">
    <%= f.label :address %><br>
    <%= f.text_field :address, class: "form-control", placeholder: "201 Brookline Ave, Boston, MA 02215" %>
  </div>
  <div class="form-group">
    <%= f.label :phone %><br>
    <%= f.text_field :phone, class: "form-control", placeholder: "617-247-0174" %>
  </div>
  <div class="form-group">
    <%= f.label :website %><br>
    <%= f.text_field :website, class: "form-control", placeholder: "http://www.panerabread.com" %>
  </div>
  <div class="form-group">
    <%= f.label :image %><br>
    <%= f.file_field :image, class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Editing Restaurant</h1>

<%= render 'form' %>

<%= link_to 'Show', @restaurant, class: "btn btn-link" %> |
<%= link_to 'Back', restaurants_path, class: "btn btn-link" %>

app/views/restaurants/index.html.erb
<div class="jumbotron">
  <h2>The Greasy Spoon is the best way to find local restaurants.</h2>
  <h3>Explore the favorite diners, pastry shops, and eateries in your community.<br>Leave reviews and ratings for your fellow foodies.</h3>
</div>


<table class="table table-hover table-condensed">
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Phone</th>
      <th>Website</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody class="restaurants">
    <% @restaurants.each do |restaurant| %>
      <tr>
        <td><%= link_to restaurant.name, restaurant, class: "btn btn-link" %></td>
        <td><%= restaurant.address %></td>
        <td><%= restaurant.phone %></td>
        <td><%= link_to restaurant.website, restaurant.website, class: "btn btn-link" %></td>
        <% if user_signed_in? && current_user.admin? %>
          <td><%= link_to 'Edit', edit_restaurant_path(restaurant), class: "btn btn-link" %></td>
          <td><%= link_to 'Destroy', restaurant, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-link" %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @restaurants, renderer: BootstrapPagination::Rails %>
<br>
<% if user_signed_in? && current_user.admin? %>
  <%= link_to 'New Restaurant', new_restaurant_path, class: "btn btn-link" %>
<% end %>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>

<%= render 'form' %>

<%= link_to 'Back', restaurants_path, class: "btn btn-link" %>

app/views/restaurants/search.html.erb
<table class="table table-hover table-condensed">
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Phone</th>
      <th>Website</th>
      <% if user_signed_in? && current_user.admin? %>
        <th colspan="2"></th>
      <% end %>
    </tr>
  </thead>

  <tbody class="restaurants">
    <% @restaurants.each do |restaurant| %>
      <tr>
        <td><%= link_to restaurant.name, restaurant %></td>
        <td><%= restaurant.address %></td>
        <td><%= restaurant.phone %></td>
        <td><%= link_to restaurant.website, restaurant.website %></td>
        <% if user_signed_in? && current_user.admin? %>
          <td><%= link_to "Edit", edit_restaurant_path(restaurant), class: "btn btn-link" %></td>
          <td><%= link_to "Destroy", restaurant, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-link" %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @restaurants, renderer: BootstrapPagination::Rails %>

app/views/restaurants/show.html.erb
<div class="row">
  <div class="col-md-3">
    <%= image_tag @restaurant.image_url %>
    <h2>
      <%= @restaurant.name %>
    </h2>

    <div class="star-rating" data-score= <%= @avg_rating %> ></div>
    <p><%= "#{@reviews.length} reviews" %></p>

    <p>
      <strong>Address:</strong>
      <%= @restaurant.address %>
    </p>

    <p>
      <strong>Phone:</strong>
      <%= @restaurant.phone %>
    </p>

    <p>
      <strong>Website:</strong>
      <%= link_to @restaurant.website, @restaurant.website %>
    </p>

    <div class="btn-group" role="group">
      <%= link_to "Write Review", new_restaurant_review_path(@restaurant), class: "btn btn-primary" %>
      <%= link_to 'Back', restaurants_path, class: "btn btn-default" %>
    </div>

    <br>
    <br>

    <iframe
      width="250"
      height="250"
      frameborder="0"
      style="border:0" src="https://www.google.com/maps/embed/v1/place?key=<%= ENV['google_maps_api'] %>&q=<%= @restaurant.address.parameterize %>&zoom=14">
    </iframe>

    <% if user_signed_in? && current_user.admin? %>
      <%= link_to 'Edit Restaurant', edit_restaurant_path(@restaurant), class: "btn btn-default" %>
    <% end %>

  </div>
  <div class="col-md-9">
    <% if @reviews.blank? %>
      <h3>No Reviews yet. Be the first to write one!</h3>
    <% else %>
    <table class="table">
      <thead>
        <tr>
          <th class="col-md-3"></th>
          <th class="col-md-9"></th>
        </tr>
      </thead>
      <tbody>
        <% @reviews.each do |review| %>
        <tr>
          <td>
            <h5>
              <%= "#{review.user.first_name.capitalize} #{review.user.last_name.capitalize[0]}" %>
            </h5>
            <p><%= review.created_at.strftime("%-m/%-d/%-y") %></p>
            <% if user_signed_in? %>
              <% if (review.user == current_user) || (current_user.admin?) %>
                <%= link_to "Edit", edit_restaurant_review_path(@restaurant, review) %> |
                <%= link_to "Delete", restaurant_review_path(@restaurant, review), method: :delete %>
              <% end %>
            <% end %>
          </td>
          <td>
            <div class="star-rating" data-score= <%= review.rating %> ></div>
            <p><%= h(review.comment).gsub(/\n/, '<br>').html_safe %></p>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
    <% end %>
  </div>
</div>

app/views/reviews/_form.html.erb
<%= form_for([@restaurant, @review]) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation" class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
        <span class="sr-only">Close</span>
      </button>
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <div id="star-rating"></div>
  </div>
  <div class="form-group">
    <%= f.label :comment %>
    <%= f.text_area :comment, class: 'form-control' %>
  </div>
  <div class="actions">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form' %>

<%= link_to 'Back', restaurant_path(@restaurant) %>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form' %>

<%= link_to 'Back', restaurant_path(@restaurant) %>